# Generated by Django 5.2.16 on 2026-07-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('available_copies__lte', models.F('total_copies'))), name='book_available_lte_total'),
        ),
    ]
