# Generated by Django 5.2.16 on 2026-07-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_harden_constraints"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="book",
            name="books_book_isbn_54becd_idx",
        ),
    ]
