# Generated by Django 5.2.16 on 2026-07-19 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_harden_constraints'),
        ('borrowing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowrecord',
            name='unique_active_borrow_per_member_book',
        ),
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['BORROWED', 'OVERDUE', 'LOST'])), fields=('member', 'book'), name='unique_active_borrow_per_member_book'),
        ),
    ]
