# Generated by Django 5.2.16 on 2026-07-19 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_aplus_indexes'),
        ('borrowing', '0002_harden_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='borrowrecord',
            name='borrowing_b_status_4f1f75_idx',
        ),
        migrations.RemoveIndex(
            model_name='borrowrecord',
            name='borrowing_b_due_dat_e330f9_idx',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('LOST', 'Lost')], db_index=True, default='BORROWED', max_length=20),
        ),
        migrations.AlterField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['status', 'due_date'], name='borrowing_b_status_419267_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['member', 'status'], name='borrowing_b_member__f6a809_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['book', 'status'], name='borrowing_b_book_id_b5f4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['status'], name='borrowing_f_status_def04b_idx'),
        ),
        migrations.AddConstraint(
            model_name='fine',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='fine_amount_non_negative'),
        ),
    ]
